name: 'React Native Android CI'

on:
  push:
    branches: [ feat/react-native ]
  pull_request:
    branches: [ feat/react-native ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    # - name: Enable Long Paths
    #   shell: powershell
    #   run: |
    #     New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `  -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force

    - name: 'Checkout code'
      uses: actions/checkout@v3

    - name: 'Relocate to Mitigate LongPaths'
      run: |
        mklink /J D:\_ %GITHUB_WORKSPACE%
      shell: cmd

    - name: 'Run wash.bash'
      working-directory: /d/_
      run: |
        ./scripts/wash.bash
      shell: bash

    - name: 'Run rinse.bash'
      working-directory: /d/_
      run: |
        ./scripts/rinse.bash
      shell: bash

    - name: 'Run repeat.bash'
      working-directory: /d/_
      run: |
        ./scripts/repeat.bash
      shell: bash
