name: 'React Native Android CI'

on:
  push:
    branches: [ feat/react-native ]
  pull_request:
    branches: [ feat/react-native ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    # - name: Enable Long Paths
    #   shell: powershell
    #   run: |
    #     New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `  -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force

    - name: 'Checkout code'
      uses: actions/checkout@v3
      with:
        path: _

    - name: 'Relocate to Mitigate LongPaths'
      run: |
        move _ D:\
      shell: cmd

    - name: 'Run wash.bash'
      run: |
        cd /d/_ && ./scripts/wash.bash
      shell: bash

    - name: 'Run rinse.bash'
      run: |
        cd /d/_ && ./scripts/rinse.bash
      shell: bash

    - name: 'Run repeat.bash'
      run: |
        cd /d/_ && ./scripts/repeat.bash
      shell: bash

    - name: 'Run shine.bash'
      run: |
        cd /d/_ && ./scripts/shine.bash
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-build-artifact
        path: d:/_/dist/AwesomeProject-debug.apk
        retention-days: 5 # Optional: specify how long to keep the artifactZ

    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    #   with:
    #     limit-access-to-actor: true
